### ISSUE TITLE
New pop-up dialog appears

### ISSUE THREAD

**Issue by tdox** [crittermike/shortkeys#620]
HI Mike,

We at [Olyns](http://www.olyns.com/) have been using your Chrome plugin on our recycling Cubes for a couple of years now.  Up until today, it has worked flawlessly, so thanks very much for your efforts.

 Today we noticed this pop-up dialog appear on the screen that our users view:

![IMG_6738](https://github.com/crittermike/shortkeys/assets/5383456/c5ec634d-d93a-4542-b90d-a703070e2190)

There is no keyboard or mouse connected to the computer that displays this Chrome page.  We tried rebooting the computer but the dialog is still displayed.

Is there a good way to remove this dialog or have it not appear?

Thanks

Tad Doxsee
Head of Software
Olyns, Inc.
(650) 521-4981

**Comment by crittermike** [comment]
Uh oh! That's coming from Chrome because I released an updated version which has slightly different permissions, and Chrome automatically disables extensions when they change permissions, and you must manually re-enable them. 

Unfortunately, there's nothing I can do about that from my side. The permission changes were necessary in order to update the extension to manifest v3 which has a hard deadline of June of this year (set by Google).

**Comment by tdox** [comment]
That makes sense.  But there's one thing I don't understand:

I see that you added "notifications" to your permissions.

![image](https://github.com/crittermike/shortkeys/assets/5383456/ef082e03-0f44-4e34-b20a-de057f7b6962)

But why am I seeing the message about "Read and change all your data on the websites you visit.  "  ?

This page (https://developer.chrome.com/docs/extensions/reference/permissions-list) explains that it's need for pageCapture

> "pageCapture"
> Gives access to the [chrome.pageCapture](https://developer.chrome.com/docs/extensions/reference/api/pageCapture) API.
> Warning displayed: Read and change all your data on all websites.

(The wording is a little different.)

I don't see that in your permissions list.

**Comment by tdox** [comment]
It looks like it came in through the "debugger" permission.
